// <auto-generated />
using System;
using Contract.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contract.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190918141918_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contracts.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("FactCost");

                    b.Property<DateTime?>("FactDeliveryDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlanCost");

                    b.Property<DateTime?>("PlanDeliveryDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("ContractId");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("Contracts.Models.Stage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("MinCntDays");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("StageId");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("Contracts.Models.StageContract", b =>
                {
                    b.Property<int>("ContractId");

                    b.Property<int>("StageId");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("FactCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProjCompletionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ContractId", "StageId");

                    b.HasIndex("StageId");

                    b.ToTable("StageContract");
                });

            modelBuilder.Entity("Contracts.Models.StageContract", b =>
                {
                    b.HasOne("Contracts.Models.Contract", "Contract")
                        .WithMany("StageContracts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Contracts.Models.Stage", "Stage")
                        .WithMany("StageContracts")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
